---
title: "Data science in the Tidyverse - Solutions"
author: "Utrecht University RDM support"
output:
  html_document:
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

```{r} 
library(tidyverse)
library(readxl)
```


# Chapter 1: Importing data

## Exercise 1
```{r}
penguins <- read_delim(file = "data/penguins_raw.tsv",
                       delim = "\t")
```


## Exercise 2
```{r}
penguins <- read_delim(file = "data/penguins_raw.tsv",
                       delim = "\t",
                       col_types = cols(`Date Egg` = col_date(format = "%d/%m/%Y")))
```

## Exercise 3
```{r}
penguins_isotopes <- read_excel(path = "data/penguins_isotopes.xlsx")
```

## Exercise 4
```{r}
write_delim(penguins_isotopes,
            file = "data/penguins_isotopes.csv",
            delim = ";")
```


# Chapter 2: Subsetting and mutating

## Exercise 5
```{r}
# option 1: filtering on the presence of MALE and FEMALE
penguins_subset <- filter(penguins, Sex %in% c("MALE", "FEMALE"))

# option 2: filtering on the absence of NA
penguins_subset <- filter(penguins, !is.na(Sex))
```

## Exercise 6
```{r}
penguins_subset <- select(penguins_subset, 
                  `Individual ID`, Species, Sex, Island, starts_with("Culmen"))
```

## Exercise 7
```{r}
penguins_subset <- penguins %>%
  filter(!is.na(Sex)) %>%
  select(`Individual ID`, Species, Sex, Island, starts_with("Culmen"))
```


## Exercise 8
```{r}
penguins_subset <- mutate(penguins_subset,
                          culmen_ratio = `Culmen Length (mm)` / `Culmen Depth (mm)`)
```


# Chapter 3: Tidy & transform

## Exercise 9
```{r}
penguins_long <- penguins_subset %>%
  rename(length = `Culmen Length (mm)`,
         depth = `Culmen Depth (mm)`) %>%
  pivot_longer(cols = c(length, depth),
               names_to = "culmen_element",
               values_to = "measurement")
```

## Exercise 10
```{r}
penguins_summary <- penguins_long %>%
  group_by(Species, culmen_element) %>%
  summarize(avg = mean(measurement),
            sd = sd(measurement))
```


## Exercise 11
```{r}
penguins_join <- full_join(penguins_long, penguins_summary,
                           by = c("Species", "culmen_element"))
```

## Exercise 12
```{r}
penguins_join <- penguins_join %>%
  mutate(zscore = (measurement - avg)/sd)
```


# Chapter 4: Data visualization

## Exercise 13

### a)
```{r}
p1 <- penguins_summary %>%
  ggplot(aes(x = culmen_element,
             y = avg,
             fill = Species)) +
  geom_bar(position = position_dodge(),
           stat = "identity")

p1
```

### b)
```{r}
p2 <- p1 +
  geom_errorbar(aes(ymin=avg-sd,
                  ymax=avg+sd),
              width=.1,
              position=position_dodge(.9))

p2
```

### c)
```{r}
p3 <- p2 +
  labs(title = "Measuring penguin bills",
       x = "Bill measurement",
       y = "Size (mm)") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  theme_bw()

p3
```


## Exercise 14

```{r}
penguins_clean <- penguins %>%
  filter(!is.na(`Culmen Length (mm)`),  # to prevent a warning message when plotting NAs
         !is.na(Sex))                   # to ensure proper categorization into facets
```


### a)
```{r}
p4 <- penguins_clean %>%
  ggplot(aes(x = `Culmen Length (mm)`,
             y = `Culmen Depth (mm)`,
             color = Species)) +
  geom_point() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  theme_bw()
  
p4
```

### b)
```{r}

p5 <- p4 +
  stat_density_2d()

p5

```



### c)
```{r}

p6 <- p4 +
  facet_grid(Island ~ Sex)
  
p6

```


## Exercise 15
```{r}

penguins_join %>%
  ggplot(aes(x = zscore, color = Species)) +
  geom_density() +
  facet_wrap("culmen_element", ncol = 1) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Distribution of culmen measurements",
       x = "z-score") +
  theme_bw()

```
