ame: Publish Website

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'book/**'

jobs:
  quarto:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          tinytex: true

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::quarto
            any::tidyverse
            any::readxl

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Render Website
        run: quarto render book/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book/_book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
